{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "ad891977-e943-401f-bf9d-0d92c57750e6",
   "metadata": {},
   "source": [
    "# ***Data Analysis***"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "170868fd-9d67-4813-8ae0-bd3129b3679c",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Importing Libraries\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import sys\n",
    "import seaborn as sns\n",
    "import os\n",
    "import matplotlib.pyplot as plt\n",
    "sys.path.append('../..')\n",
    "from scripts import project_functions as pf\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "82d76347-0297-4864-9024-aac1b3028ddd",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Game</th>\n",
       "      <th>Year</th>\n",
       "      <th>Genre</th>\n",
       "      <th>Publisher</th>\n",
       "      <th>North America</th>\n",
       "      <th>Europe</th>\n",
       "      <th>Japan</th>\n",
       "      <th>Rest of World</th>\n",
       "      <th>Global</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Grand Theft Auto V</td>\n",
       "      <td>2014.0</td>\n",
       "      <td>Action</td>\n",
       "      <td>Rockstar Games</td>\n",
       "      <td>6.06</td>\n",
       "      <td>9.71</td>\n",
       "      <td>0.60</td>\n",
       "      <td>3.02</td>\n",
       "      <td>19.39</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Call of Duty: Black Ops 3</td>\n",
       "      <td>2015.0</td>\n",
       "      <td>Shooter</td>\n",
       "      <td>Activision</td>\n",
       "      <td>6.18</td>\n",
       "      <td>6.05</td>\n",
       "      <td>0.41</td>\n",
       "      <td>2.44</td>\n",
       "      <td>15.09</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Red Dead Redemption 2</td>\n",
       "      <td>2018.0</td>\n",
       "      <td>Action-Adventure</td>\n",
       "      <td>Rockstar Games</td>\n",
       "      <td>5.26</td>\n",
       "      <td>6.21</td>\n",
       "      <td>0.21</td>\n",
       "      <td>2.26</td>\n",
       "      <td>13.94</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Call of Duty: WWII</td>\n",
       "      <td>2017.0</td>\n",
       "      <td>Shooter</td>\n",
       "      <td>Activision</td>\n",
       "      <td>4.67</td>\n",
       "      <td>6.21</td>\n",
       "      <td>0.40</td>\n",
       "      <td>2.12</td>\n",
       "      <td>13.40</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>FIFA 18</td>\n",
       "      <td>2017.0</td>\n",
       "      <td>Sports</td>\n",
       "      <td>EA Sports</td>\n",
       "      <td>1.27</td>\n",
       "      <td>8.64</td>\n",
       "      <td>0.15</td>\n",
       "      <td>1.73</td>\n",
       "      <td>11.80</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1029</th>\n",
       "      <td>Fallen Legion: Flames of Rebellion</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Role-Playing</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1030</th>\n",
       "      <td>Radial G Racing Revolved</td>\n",
       "      <td>2017.0</td>\n",
       "      <td>Racing</td>\n",
       "      <td>Tammeka Games</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1031</th>\n",
       "      <td>The Mummy Demastered</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Action</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1032</th>\n",
       "      <td>Project Nimbus: Code Mirai</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Action</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1033</th>\n",
       "      <td>Battle Chef Brigade</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Action</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1034 rows × 9 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                    Game    Year             Genre  \\\n",
       "0                     Grand Theft Auto V  2014.0            Action   \n",
       "1              Call of Duty: Black Ops 3  2015.0           Shooter   \n",
       "2                  Red Dead Redemption 2  2018.0  Action-Adventure   \n",
       "3                     Call of Duty: WWII  2017.0           Shooter   \n",
       "4                                FIFA 18  2017.0            Sports   \n",
       "...                                  ...     ...               ...   \n",
       "1029  Fallen Legion: Flames of Rebellion     NaN      Role-Playing   \n",
       "1030            Radial G Racing Revolved  2017.0            Racing   \n",
       "1031                The Mummy Demastered     NaN            Action   \n",
       "1032          Project Nimbus: Code Mirai     NaN            Action   \n",
       "1033                 Battle Chef Brigade     NaN            Action   \n",
       "\n",
       "           Publisher  North America  Europe  Japan  Rest of World  Global  \n",
       "0     Rockstar Games           6.06    9.71   0.60           3.02   19.39  \n",
       "1         Activision           6.18    6.05   0.41           2.44   15.09  \n",
       "2     Rockstar Games           5.26    6.21   0.21           2.26   13.94  \n",
       "3         Activision           4.67    6.21   0.40           2.12   13.40  \n",
       "4          EA Sports           1.27    8.64   0.15           1.73   11.80  \n",
       "...              ...            ...     ...    ...            ...     ...  \n",
       "1029             NaN           0.00    0.00   0.00           0.00    0.00  \n",
       "1030   Tammeka Games           0.00    0.00   0.00           0.00    0.00  \n",
       "1031             NaN           0.00    0.00   0.00           0.00    0.00  \n",
       "1032             NaN           0.00    0.00   0.00           0.00    0.00  \n",
       "1033             NaN           0.00    0.00   0.00           0.00    0.00  \n",
       "\n",
       "[1034 rows x 9 columns]"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "PS4ds = pf.load_and_process(\"/Users/sakshamrana/project-group12-project/data/raw/PS4_GamesSales.csv\")\n",
    "PS4ds"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "29a57fb8-9111-4862-be86-a8c937577c04",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Pos</th>\n",
       "      <th>Game</th>\n",
       "      <th>Year</th>\n",
       "      <th>Genre</th>\n",
       "      <th>Publisher</th>\n",
       "      <th>North America</th>\n",
       "      <th>Europe</th>\n",
       "      <th>Japan</th>\n",
       "      <th>Rest of World</th>\n",
       "      <th>Global</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>Grand Theft Auto V</td>\n",
       "      <td>2014.0</td>\n",
       "      <td>Action</td>\n",
       "      <td>Rockstar Games</td>\n",
       "      <td>4.70</td>\n",
       "      <td>3.25</td>\n",
       "      <td>0.01</td>\n",
       "      <td>0.76</td>\n",
       "      <td>8.72</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>Call of Duty: Black Ops 3</td>\n",
       "      <td>2015.0</td>\n",
       "      <td>Shooter</td>\n",
       "      <td>Activision</td>\n",
       "      <td>4.63</td>\n",
       "      <td>2.04</td>\n",
       "      <td>0.02</td>\n",
       "      <td>0.68</td>\n",
       "      <td>7.37</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>Call of Duty: WWII</td>\n",
       "      <td>2017.0</td>\n",
       "      <td>Shooter</td>\n",
       "      <td>Activision</td>\n",
       "      <td>3.75</td>\n",
       "      <td>1.91</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.57</td>\n",
       "      <td>6.23</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>Red Dead Redemption 2</td>\n",
       "      <td>2018.0</td>\n",
       "      <td>Action-Adventure</td>\n",
       "      <td>Rockstar Games</td>\n",
       "      <td>3.76</td>\n",
       "      <td>1.47</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.54</td>\n",
       "      <td>5.77</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>MineCraft</td>\n",
       "      <td>2014.0</td>\n",
       "      <td>Misc</td>\n",
       "      <td>Microsoft Studios</td>\n",
       "      <td>3.23</td>\n",
       "      <td>1.71</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.49</td>\n",
       "      <td>5.43</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>608</th>\n",
       "      <td>609</td>\n",
       "      <td>Biomutant</td>\n",
       "      <td>2018.0</td>\n",
       "      <td>Action</td>\n",
       "      <td>THQ Nordic</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>609</th>\n",
       "      <td>610</td>\n",
       "      <td>Biomutant</td>\n",
       "      <td>2019.0</td>\n",
       "      <td>Action</td>\n",
       "      <td>THQ Nordic</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>610</th>\n",
       "      <td>611</td>\n",
       "      <td>de Blob</td>\n",
       "      <td>2017.0</td>\n",
       "      <td>Platform</td>\n",
       "      <td>THQ Nordic</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>611</th>\n",
       "      <td>612</td>\n",
       "      <td>Outcast: Second Contact</td>\n",
       "      <td>2017.0</td>\n",
       "      <td>Adventure</td>\n",
       "      <td>Bigben Interactive</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>612</th>\n",
       "      <td>613</td>\n",
       "      <td>Code Vein</td>\n",
       "      <td>2019.0</td>\n",
       "      <td>Action</td>\n",
       "      <td>Bandai Namco Entertainment</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>613 rows × 10 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     Pos                       Game    Year             Genre  \\\n",
       "0      1         Grand Theft Auto V  2014.0            Action   \n",
       "1      2  Call of Duty: Black Ops 3  2015.0           Shooter   \n",
       "2      3         Call of Duty: WWII  2017.0           Shooter   \n",
       "3      4      Red Dead Redemption 2  2018.0  Action-Adventure   \n",
       "4      5                  MineCraft  2014.0              Misc   \n",
       "..   ...                        ...     ...               ...   \n",
       "608  609                  Biomutant  2018.0            Action   \n",
       "609  610                  Biomutant  2019.0            Action   \n",
       "610  611                    de Blob  2017.0          Platform   \n",
       "611  612    Outcast: Second Contact  2017.0         Adventure   \n",
       "612  613                  Code Vein  2019.0            Action   \n",
       "\n",
       "                      Publisher  North America  Europe  Japan  Rest of World  \\\n",
       "0                Rockstar Games           4.70    3.25   0.01           0.76   \n",
       "1                    Activision           4.63    2.04   0.02           0.68   \n",
       "2                    Activision           3.75    1.91   0.00           0.57   \n",
       "3                Rockstar Games           3.76    1.47   0.00           0.54   \n",
       "4             Microsoft Studios           3.23    1.71   0.00           0.49   \n",
       "..                          ...            ...     ...    ...            ...   \n",
       "608                  THQ Nordic           0.00    0.00   0.00           0.00   \n",
       "609                  THQ Nordic           0.00    0.00   0.00           0.00   \n",
       "610                  THQ Nordic           0.00    0.00   0.00           0.00   \n",
       "611          Bigben Interactive           0.00    0.00   0.00           0.00   \n",
       "612  Bandai Namco Entertainment           0.00    0.00   0.00           0.00   \n",
       "\n",
       "     Global  \n",
       "0      8.72  \n",
       "1      7.37  \n",
       "2      6.23  \n",
       "3      5.77  \n",
       "4      5.43  \n",
       "..      ...  \n",
       "608    0.00  \n",
       "609    0.00  \n",
       "610    0.00  \n",
       "611    0.00  \n",
       "612    0.00  \n",
       "\n",
       "[613 rows x 10 columns]"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "xBoxds = pf.load_and_process(\"/Users/sakshamrana/project-group12-project/data/raw/XboxOne_GameSales.csv\")\n",
    "xBoxds"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "e6fabaf0-8224-4bc9-bd7d-ceaf2f1bf9d0",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Pos</th>\n",
       "      <th>Game</th>\n",
       "      <th>Year</th>\n",
       "      <th>Genre</th>\n",
       "      <th>Publisher</th>\n",
       "      <th>North America</th>\n",
       "      <th>Europe</th>\n",
       "      <th>Japan</th>\n",
       "      <th>Rest of World</th>\n",
       "      <th>Global</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>Grand Theft Auto V</td>\n",
       "      <td>2014.0</td>\n",
       "      <td>Action</td>\n",
       "      <td>Rockstar Games</td>\n",
       "      <td>4.70</td>\n",
       "      <td>3.25</td>\n",
       "      <td>0.01</td>\n",
       "      <td>0.76</td>\n",
       "      <td>8.72</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>Call of Duty: Black Ops 3</td>\n",
       "      <td>2015.0</td>\n",
       "      <td>Shooter</td>\n",
       "      <td>Activision</td>\n",
       "      <td>4.63</td>\n",
       "      <td>2.04</td>\n",
       "      <td>0.02</td>\n",
       "      <td>0.68</td>\n",
       "      <td>7.37</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>Call of Duty: WWII</td>\n",
       "      <td>2017.0</td>\n",
       "      <td>Shooter</td>\n",
       "      <td>Activision</td>\n",
       "      <td>3.75</td>\n",
       "      <td>1.91</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.57</td>\n",
       "      <td>6.23</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>Red Dead Redemption 2</td>\n",
       "      <td>2018.0</td>\n",
       "      <td>Action-Adventure</td>\n",
       "      <td>Rockstar Games</td>\n",
       "      <td>3.76</td>\n",
       "      <td>1.47</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.54</td>\n",
       "      <td>5.77</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>MineCraft</td>\n",
       "      <td>2014.0</td>\n",
       "      <td>Misc</td>\n",
       "      <td>Microsoft Studios</td>\n",
       "      <td>3.23</td>\n",
       "      <td>1.71</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.49</td>\n",
       "      <td>5.43</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>608</th>\n",
       "      <td>609</td>\n",
       "      <td>Biomutant</td>\n",
       "      <td>2018.0</td>\n",
       "      <td>Action</td>\n",
       "      <td>THQ Nordic</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>609</th>\n",
       "      <td>610</td>\n",
       "      <td>Biomutant</td>\n",
       "      <td>2019.0</td>\n",
       "      <td>Action</td>\n",
       "      <td>THQ Nordic</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>610</th>\n",
       "      <td>611</td>\n",
       "      <td>de Blob</td>\n",
       "      <td>2017.0</td>\n",
       "      <td>Platform</td>\n",
       "      <td>THQ Nordic</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>611</th>\n",
       "      <td>612</td>\n",
       "      <td>Outcast: Second Contact</td>\n",
       "      <td>2017.0</td>\n",
       "      <td>Adventure</td>\n",
       "      <td>Bigben Interactive</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>612</th>\n",
       "      <td>613</td>\n",
       "      <td>Code Vein</td>\n",
       "      <td>2019.0</td>\n",
       "      <td>Action</td>\n",
       "      <td>Bandai Namco Entertainment</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>613 rows × 10 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     Pos                       Game    Year             Genre  \\\n",
       "0      1         Grand Theft Auto V  2014.0            Action   \n",
       "1      2  Call of Duty: Black Ops 3  2015.0           Shooter   \n",
       "2      3         Call of Duty: WWII  2017.0           Shooter   \n",
       "3      4      Red Dead Redemption 2  2018.0  Action-Adventure   \n",
       "4      5                  MineCraft  2014.0              Misc   \n",
       "..   ...                        ...     ...               ...   \n",
       "608  609                  Biomutant  2018.0            Action   \n",
       "609  610                  Biomutant  2019.0            Action   \n",
       "610  611                    de Blob  2017.0          Platform   \n",
       "611  612    Outcast: Second Contact  2017.0         Adventure   \n",
       "612  613                  Code Vein  2019.0            Action   \n",
       "\n",
       "                      Publisher  North America  Europe  Japan  Rest of World  \\\n",
       "0                Rockstar Games           4.70    3.25   0.01           0.76   \n",
       "1                    Activision           4.63    2.04   0.02           0.68   \n",
       "2                    Activision           3.75    1.91   0.00           0.57   \n",
       "3                Rockstar Games           3.76    1.47   0.00           0.54   \n",
       "4             Microsoft Studios           3.23    1.71   0.00           0.49   \n",
       "..                          ...            ...     ...    ...            ...   \n",
       "608                  THQ Nordic           0.00    0.00   0.00           0.00   \n",
       "609                  THQ Nordic           0.00    0.00   0.00           0.00   \n",
       "610                  THQ Nordic           0.00    0.00   0.00           0.00   \n",
       "611          Bigben Interactive           0.00    0.00   0.00           0.00   \n",
       "612  Bandai Namco Entertainment           0.00    0.00   0.00           0.00   \n",
       "\n",
       "     Global  \n",
       "0      8.72  \n",
       "1      7.37  \n",
       "2      6.23  \n",
       "3      5.77  \n",
       "4      5.43  \n",
       "..      ...  \n",
       "608    0.00  \n",
       "609    0.00  \n",
       "610    0.00  \n",
       "611    0.00  \n",
       "612    0.00  \n",
       "\n",
       "[613 rows x 10 columns]"
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ds = pd.read_csv(\"/Users/sakshamrana/project-group12-project/data/raw/XboxOne_GameSales.csv\")\n",
    "ds"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e43a55d9-53b8-4892-b707-dcb604164f69",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "b2bf2d34-fb6b-47da-ac87-5dafc8361331",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>North America</th>\n",
       "      <th>Europe</th>\n",
       "      <th>Japan</th>\n",
       "      <th>Rest of World</th>\n",
       "      <th>Global</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Publisher</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>2K Games</th>\n",
       "      <td>2.93</td>\n",
       "      <td>3.62</td>\n",
       "      <td>0.18</td>\n",
       "      <td>1.28</td>\n",
       "      <td>8.03</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2K Sports</th>\n",
       "      <td>10.22</td>\n",
       "      <td>3.96</td>\n",
       "      <td>0.14</td>\n",
       "      <td>3.05</td>\n",
       "      <td>17.36</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3D Realms</th>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>505 Games</th>\n",
       "      <td>1.26</td>\n",
       "      <td>2.21</td>\n",
       "      <td>0.07</td>\n",
       "      <td>0.66</td>\n",
       "      <td>4.19</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5pb</th>\n",
       "      <td>0.03</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.08</td>\n",
       "      <td>0.01</td>\n",
       "      <td>0.12</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Warner Bros. Interactive Entertainment</th>\n",
       "      <td>10.16</td>\n",
       "      <td>12.88</td>\n",
       "      <td>0.30</td>\n",
       "      <td>4.52</td>\n",
       "      <td>27.83</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Wired Productions</th>\n",
       "      <td>0.06</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.02</td>\n",
       "      <td>0.08</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Xseed Games</th>\n",
       "      <td>0.06</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.01</td>\n",
       "      <td>0.01</td>\n",
       "      <td>0.08</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Yacht Club Games</th>\n",
       "      <td>0.08</td>\n",
       "      <td>0.04</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.02</td>\n",
       "      <td>0.14</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Yeti</th>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.03</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.03</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>152 rows × 5 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                        North America  Europe  Japan  \\\n",
       "Publisher                                                              \n",
       "2K Games                                         2.93    3.62   0.18   \n",
       "2K Sports                                       10.22    3.96   0.14   \n",
       "3D Realms                                        0.00    0.00   0.00   \n",
       "505 Games                                        1.26    2.21   0.07   \n",
       "5pb                                              0.03    0.00   0.08   \n",
       "...                                               ...     ...    ...   \n",
       "Warner Bros. Interactive Entertainment          10.16   12.88   0.30   \n",
       "Wired Productions                                0.06    0.00   0.00   \n",
       "Xseed Games                                      0.06    0.00   0.01   \n",
       "Yacht Club Games                                 0.08    0.04   0.00   \n",
       "Yeti                                             0.00    0.00   0.03   \n",
       "\n",
       "                                        Rest of World  Global  \n",
       "Publisher                                                      \n",
       "2K Games                                         1.28    8.03  \n",
       "2K Sports                                        3.05   17.36  \n",
       "3D Realms                                        0.00    0.00  \n",
       "505 Games                                        0.66    4.19  \n",
       "5pb                                              0.01    0.12  \n",
       "...                                               ...     ...  \n",
       "Warner Bros. Interactive Entertainment           4.52   27.83  \n",
       "Wired Productions                                0.02    0.08  \n",
       "Xseed Games                                      0.01    0.08  \n",
       "Yacht Club Games                                 0.02    0.14  \n",
       "Yeti                                             0.00    0.03  \n",
       "\n",
       "[152 rows x 5 columns]"
      ]
     },
     "execution_count": 23,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "PS4ds_Publisher = PS4ds.drop(columns = 'Year').groupby(['Publisher']).sum()\n",
    "PS4ds_Publisher\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "d4899afc-f44a-47a6-8298-54d946062c11",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>North America</th>\n",
       "      <th>Europe</th>\n",
       "      <th>Japan</th>\n",
       "      <th>Rest of World</th>\n",
       "      <th>Global</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Publisher</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>11 bit studios</th>\n",
       "      <td>0.00</td>\n",
       "      <td>0.01</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.01</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2K Games</th>\n",
       "      <td>2.39</td>\n",
       "      <td>1.22</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.37</td>\n",
       "      <td>3.98</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2K Sports</th>\n",
       "      <td>8.16</td>\n",
       "      <td>1.19</td>\n",
       "      <td>0.00</td>\n",
       "      <td>1.05</td>\n",
       "      <td>10.42</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>505 Games</th>\n",
       "      <td>1.34</td>\n",
       "      <td>1.03</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.20</td>\n",
       "      <td>2.58</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5pb</th>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.02</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.02</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Versus Evil</th>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Warner Bros. Interactive Entertainment</th>\n",
       "      <td>10.01</td>\n",
       "      <td>4.74</td>\n",
       "      <td>0.02</td>\n",
       "      <td>1.50</td>\n",
       "      <td>16.23</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Wired Productions</th>\n",
       "      <td>0.02</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.02</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Wizards of the Coast</th>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Yacht Club Games</th>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>98 rows × 5 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                        North America  Europe  Japan  \\\n",
       "Publisher                                                              \n",
       "11 bit studios                                   0.00    0.01   0.00   \n",
       "2K Games                                         2.39    1.22   0.00   \n",
       "2K Sports                                        8.16    1.19   0.00   \n",
       "505 Games                                        1.34    1.03   0.00   \n",
       "5pb                                              0.00    0.00   0.02   \n",
       "...                                               ...     ...    ...   \n",
       "Versus Evil                                      0.00    0.00   0.00   \n",
       "Warner Bros. Interactive Entertainment          10.01    4.74   0.02   \n",
       "Wired Productions                                0.02    0.00   0.00   \n",
       "Wizards of the Coast                             0.00    0.00   0.00   \n",
       "Yacht Club Games                                 0.00    0.00   0.00   \n",
       "\n",
       "                                        Rest of World  Global  \n",
       "Publisher                                                      \n",
       "11 bit studios                                   0.00    0.01  \n",
       "2K Games                                         0.37    3.98  \n",
       "2K Sports                                        1.05   10.42  \n",
       "505 Games                                        0.20    2.58  \n",
       "5pb                                              0.00    0.02  \n",
       "...                                               ...     ...  \n",
       "Versus Evil                                      0.00    0.00  \n",
       "Warner Bros. Interactive Entertainment           1.50   16.23  \n",
       "Wired Productions                                0.00    0.02  \n",
       "Wizards of the Coast                             0.00    0.00  \n",
       "Yacht Club Games                                 0.00    0.00  \n",
       "\n",
       "[98 rows x 5 columns]"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "xBoxds_Publisher = xBoxds.drop(columns = 'Year').drop(columns = 'Pos').groupby(['Publisher']).sum()\n",
    "xBoxds_Publisher"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "492607ce-0c28-4885-96e7-28fb12125d2a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>North America</th>\n",
       "      <th>Europe</th>\n",
       "      <th>Japan</th>\n",
       "      <th>Rest of World</th>\n",
       "      <th>Global</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Publisher</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Microsoft Studios</th>\n",
       "      <td>25.59</td>\n",
       "      <td>14.79</td>\n",
       "      <td>0.22</td>\n",
       "      <td>3.99</td>\n",
       "      <td>44.61</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Activision</th>\n",
       "      <td>24.20</td>\n",
       "      <td>10.26</td>\n",
       "      <td>0.03</td>\n",
       "      <td>3.53</td>\n",
       "      <td>38.02</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Ubisoft</th>\n",
       "      <td>18.68</td>\n",
       "      <td>10.04</td>\n",
       "      <td>0.02</td>\n",
       "      <td>2.87</td>\n",
       "      <td>31.57</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Electronic Arts</th>\n",
       "      <td>17.35</td>\n",
       "      <td>10.22</td>\n",
       "      <td>0.09</td>\n",
       "      <td>2.70</td>\n",
       "      <td>30.37</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>EA Sports</th>\n",
       "      <td>13.62</td>\n",
       "      <td>7.01</td>\n",
       "      <td>0.00</td>\n",
       "      <td>2.05</td>\n",
       "      <td>22.69</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Ice-pick Lodge</th>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Experience Inc.</th>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>BioWare</th>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Bandai Namco Entertainment</th>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Yacht Club Games</th>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>98 rows × 5 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                            North America  Europe  Japan  Rest of World  \\\n",
       "Publisher                                                                 \n",
       "Microsoft Studios                   25.59   14.79   0.22           3.99   \n",
       "Activision                          24.20   10.26   0.03           3.53   \n",
       "Ubisoft                             18.68   10.04   0.02           2.87   \n",
       "Electronic Arts                     17.35   10.22   0.09           2.70   \n",
       "EA Sports                           13.62    7.01   0.00           2.05   \n",
       "...                                   ...     ...    ...            ...   \n",
       "Ice-pick Lodge                       0.00    0.00   0.00           0.00   \n",
       "Experience Inc.                      0.00    0.00   0.00           0.00   \n",
       "BioWare                              0.00    0.00   0.00           0.00   \n",
       "Bandai Namco Entertainment           0.00    0.00   0.00           0.00   \n",
       "Yacht Club Games                     0.00    0.00   0.00           0.00   \n",
       "\n",
       "                            Global  \n",
       "Publisher                           \n",
       "Microsoft Studios            44.61  \n",
       "Activision                   38.02  \n",
       "Ubisoft                      31.57  \n",
       "Electronic Arts              30.37  \n",
       "EA Sports                    22.69  \n",
       "...                            ...  \n",
       "Ice-pick Lodge                0.00  \n",
       "Experience Inc.               0.00  \n",
       "BioWare                       0.00  \n",
       "Bandai Namco Entertainment    0.00  \n",
       "Yacht Club Games              0.00  \n",
       "\n",
       "[98 rows x 5 columns]"
      ]
     },
     "execution_count": 25,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "xBoxds_Publisher.sort_values(by = 'Global', ascending = False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "0905fc54-0010-4e2b-8665-44151f0240f9",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>North America</th>\n",
       "      <th>Europe</th>\n",
       "      <th>Japan</th>\n",
       "      <th>Rest of World</th>\n",
       "      <th>Global</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Publisher</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Activision</th>\n",
       "      <td>28.20</td>\n",
       "      <td>30.96</td>\n",
       "      <td>1.65</td>\n",
       "      <td>11.71</td>\n",
       "      <td>72.44</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Ubisoft</th>\n",
       "      <td>18.50</td>\n",
       "      <td>29.46</td>\n",
       "      <td>1.91</td>\n",
       "      <td>9.22</td>\n",
       "      <td>59.16</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Electronic Arts</th>\n",
       "      <td>17.05</td>\n",
       "      <td>27.88</td>\n",
       "      <td>1.42</td>\n",
       "      <td>8.60</td>\n",
       "      <td>54.96</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Sony Interactive Entertainment</th>\n",
       "      <td>21.07</td>\n",
       "      <td>22.96</td>\n",
       "      <td>2.14</td>\n",
       "      <td>8.73</td>\n",
       "      <td>54.85</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>EA Sports</th>\n",
       "      <td>15.18</td>\n",
       "      <td>24.36</td>\n",
       "      <td>0.40</td>\n",
       "      <td>7.60</td>\n",
       "      <td>47.55</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>FarSight Studios</th>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Frictional Games</th>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Futurlab 1</th>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Gust</th>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Entergram</th>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>152 rows × 5 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                North America  Europe  Japan  Rest of World  \\\n",
       "Publisher                                                                     \n",
       "Activision                              28.20   30.96   1.65          11.71   \n",
       "Ubisoft                                 18.50   29.46   1.91           9.22   \n",
       "Electronic Arts                         17.05   27.88   1.42           8.60   \n",
       "Sony Interactive Entertainment          21.07   22.96   2.14           8.73   \n",
       "EA Sports                               15.18   24.36   0.40           7.60   \n",
       "...                                       ...     ...    ...            ...   \n",
       "FarSight Studios                         0.00    0.00   0.00           0.00   \n",
       "Frictional Games                         0.00    0.00   0.00           0.00   \n",
       "Futurlab 1                               0.00    0.00   0.00           0.00   \n",
       "Gust                                     0.00    0.00   0.00           0.00   \n",
       "Entergram                                0.00    0.00   0.00           0.00   \n",
       "\n",
       "                                Global  \n",
       "Publisher                               \n",
       "Activision                       72.44  \n",
       "Ubisoft                          59.16  \n",
       "Electronic Arts                  54.96  \n",
       "Sony Interactive Entertainment   54.85  \n",
       "EA Sports                        47.55  \n",
       "...                                ...  \n",
       "FarSight Studios                  0.00  \n",
       "Frictional Games                  0.00  \n",
       "Futurlab 1                        0.00  \n",
       "Gust                              0.00  \n",
       "Entergram                         0.00  \n",
       "\n",
       "[152 rows x 5 columns]"
      ]
     },
     "execution_count": 26,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "PS4ds_Publisher.sort_values(by = 'Global', ascending = False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "9d424282-4cef-4a85-ab06-b1cddd80792f",
   "metadata": {},
   "outputs": [],
   "source": [
    "xBoxds_Publisher = xBoxds_Publisher[xBoxds_Publisher.Global!= 0]\n",
    "PS4ds_Publisher = PS4ds_Publisher[PS4ds_Publisher.Global!= 0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "a3792612-d8c7-4da1-8266-acc0ae067fe2",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>North America</th>\n",
       "      <th>Europe</th>\n",
       "      <th>Japan</th>\n",
       "      <th>Rest of World</th>\n",
       "      <th>Global</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Publisher</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>11 bit studios</th>\n",
       "      <td>0.00</td>\n",
       "      <td>0.01</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.01</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2K Games</th>\n",
       "      <td>2.39</td>\n",
       "      <td>1.22</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.37</td>\n",
       "      <td>3.98</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2K Sports</th>\n",
       "      <td>8.16</td>\n",
       "      <td>1.19</td>\n",
       "      <td>0.00</td>\n",
       "      <td>1.05</td>\n",
       "      <td>10.42</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>505 Games</th>\n",
       "      <td>1.34</td>\n",
       "      <td>1.03</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.20</td>\n",
       "      <td>2.58</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5pb</th>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.02</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.02</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Tripwire Interactive</th>\n",
       "      <td>0.05</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.01</td>\n",
       "      <td>0.06</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Tru Blu Entertainment</th>\n",
       "      <td>0.00</td>\n",
       "      <td>0.07</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.07</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Ubisoft</th>\n",
       "      <td>18.68</td>\n",
       "      <td>10.04</td>\n",
       "      <td>0.02</td>\n",
       "      <td>2.87</td>\n",
       "      <td>31.57</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Warner Bros. Interactive Entertainment</th>\n",
       "      <td>10.01</td>\n",
       "      <td>4.74</td>\n",
       "      <td>0.02</td>\n",
       "      <td>1.50</td>\n",
       "      <td>16.23</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Wired Productions</th>\n",
       "      <td>0.02</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.02</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>79 rows × 5 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                        North America  Europe  Japan  \\\n",
       "Publisher                                                              \n",
       "11 bit studios                                   0.00    0.01   0.00   \n",
       "2K Games                                         2.39    1.22   0.00   \n",
       "2K Sports                                        8.16    1.19   0.00   \n",
       "505 Games                                        1.34    1.03   0.00   \n",
       "5pb                                              0.00    0.00   0.02   \n",
       "...                                               ...     ...    ...   \n",
       "Tripwire Interactive                             0.05    0.00   0.00   \n",
       "Tru Blu Entertainment                            0.00    0.07   0.00   \n",
       "Ubisoft                                         18.68   10.04   0.02   \n",
       "Warner Bros. Interactive Entertainment          10.01    4.74   0.02   \n",
       "Wired Productions                                0.02    0.00   0.00   \n",
       "\n",
       "                                        Rest of World  Global  \n",
       "Publisher                                                      \n",
       "11 bit studios                                   0.00    0.01  \n",
       "2K Games                                         0.37    3.98  \n",
       "2K Sports                                        1.05   10.42  \n",
       "505 Games                                        0.20    2.58  \n",
       "5pb                                              0.00    0.02  \n",
       "...                                               ...     ...  \n",
       "Tripwire Interactive                             0.01    0.06  \n",
       "Tru Blu Entertainment                            0.00    0.07  \n",
       "Ubisoft                                          2.87   31.57  \n",
       "Warner Bros. Interactive Entertainment           1.50   16.23  \n",
       "Wired Productions                                0.00    0.02  \n",
       "\n",
       "[79 rows x 5 columns]"
      ]
     },
     "execution_count": 28,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "xBoxds_Publisher"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "e3a1c13b-3153-40ab-a8a4-652a2d969a61",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>North America</th>\n",
       "      <th>Europe</th>\n",
       "      <th>Japan</th>\n",
       "      <th>Rest of World</th>\n",
       "      <th>Global</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Publisher</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>2K Games</th>\n",
       "      <td>2.93</td>\n",
       "      <td>3.62</td>\n",
       "      <td>0.18</td>\n",
       "      <td>1.28</td>\n",
       "      <td>8.03</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2K Sports</th>\n",
       "      <td>10.22</td>\n",
       "      <td>3.96</td>\n",
       "      <td>0.14</td>\n",
       "      <td>3.05</td>\n",
       "      <td>17.36</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>505 Games</th>\n",
       "      <td>1.26</td>\n",
       "      <td>2.21</td>\n",
       "      <td>0.07</td>\n",
       "      <td>0.66</td>\n",
       "      <td>4.19</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5pb</th>\n",
       "      <td>0.03</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.08</td>\n",
       "      <td>0.01</td>\n",
       "      <td>0.12</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Accolade</th>\n",
       "      <td>0.04</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.01</td>\n",
       "      <td>0.05</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Warner Bros. Interactive Entertainment</th>\n",
       "      <td>10.16</td>\n",
       "      <td>12.88</td>\n",
       "      <td>0.30</td>\n",
       "      <td>4.52</td>\n",
       "      <td>27.83</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Wired Productions</th>\n",
       "      <td>0.06</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.02</td>\n",
       "      <td>0.08</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Xseed Games</th>\n",
       "      <td>0.06</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.01</td>\n",
       "      <td>0.01</td>\n",
       "      <td>0.08</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Yacht Club Games</th>\n",
       "      <td>0.08</td>\n",
       "      <td>0.04</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.02</td>\n",
       "      <td>0.14</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Yeti</th>\n",
       "      <td>0.00</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.03</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.03</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>119 rows × 5 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                        North America  Europe  Japan  \\\n",
       "Publisher                                                              \n",
       "2K Games                                         2.93    3.62   0.18   \n",
       "2K Sports                                       10.22    3.96   0.14   \n",
       "505 Games                                        1.26    2.21   0.07   \n",
       "5pb                                              0.03    0.00   0.08   \n",
       "Accolade                                         0.04    0.00   0.00   \n",
       "...                                               ...     ...    ...   \n",
       "Warner Bros. Interactive Entertainment          10.16   12.88   0.30   \n",
       "Wired Productions                                0.06    0.00   0.00   \n",
       "Xseed Games                                      0.06    0.00   0.01   \n",
       "Yacht Club Games                                 0.08    0.04   0.00   \n",
       "Yeti                                             0.00    0.00   0.03   \n",
       "\n",
       "                                        Rest of World  Global  \n",
       "Publisher                                                      \n",
       "2K Games                                         1.28    8.03  \n",
       "2K Sports                                        3.05   17.36  \n",
       "505 Games                                        0.66    4.19  \n",
       "5pb                                              0.01    0.12  \n",
       "Accolade                                         0.01    0.05  \n",
       "...                                               ...     ...  \n",
       "Warner Bros. Interactive Entertainment           4.52   27.83  \n",
       "Wired Productions                                0.02    0.08  \n",
       "Xseed Games                                      0.01    0.08  \n",
       "Yacht Club Games                                 0.02    0.14  \n",
       "Yeti                                             0.00    0.03  \n",
       "\n",
       "[119 rows x 5 columns]"
      ]
     },
     "execution_count": 29,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "PS4ds_Publisher"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e2e68464-3d34-47c4-86b1-a3c536451b0b",
   "metadata": {},
   "source": [
    "# ***3) Plotting Graphs***"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "32a61cb0-8847-43ea-8a0b-561fa9c7e42b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Text(0.5, 1.0, 'PS4 Sales by Publishers')"
      ]
     },
     "execution_count": 30,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXgAAAEWCAYAAABsY4yMAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAAAfq0lEQVR4nO3debgcVbnv8e8vYQhDwpQIMiRhRuBAlI0KeJkPIoIiDsgVENQTUQFRIOq5KqBHj+KEiAIRJYCCzAiozIQwQ8IYJkUIhOCWhBCZIpDw3j/W2tmdze7u2kP13qn8Ps/TT1d3Va31dnX126tXVa1WRGBmZtUzZKADMDOzcjjBm5lVlBO8mVlFOcGbmVWUE7yZWUU5wZuZVZQTvC1xJE2W9LnBXmYvYpgk6X8azA9JG+Xp0yR9q0CZMyTt3p9x2pLDCd4WkxPCfEkvS/qnpDMlrZznbSHpGkkvSJonaZqkvbop47icjOomlqJlLWkkjc2v/eV8myHp6/1dT0QcFhHf7e9yrVqc4K07+0TEysC7gG2Bb+bnrwCuBdYE3gYcCbxYu6KkDYGPAf9oUkfTspZwq+ZteADwbUl7DnRAfSFpmYGOwXrOCd7qiohZwF+ALSWNBNYHfh0Rr+fbrRFxS5fVTgG+Brxer9xmZUlaTdKVkmbnFv6VktZtUN5nJD2Sl71a0pj8vCT9TNJzkv4l6QFJWzZ4yRtKuisv+0dJq+dy/iTpiC51PiBp3wZlARARtwMPkbbhIZIW21613S7ZSEnXSnpJ0k0dr6Wb17yoO0fSyLyN5kmaK+lmSbWf7XE53n9JOl/SsJpy9pZ0X173Nklb1cybIelrkh4AXpG0TH48K8f3mKTdmm0DGzhO8FaXpPWAvYB7geeBx4HfSdpX0prdLP9x4PWI+HOTopuVNQQ4ExgDjAbmk744uotxX+C/gf2AUcDNwHl59h7AjsAmwKrA/rnueg4GPgOsDSwATs7PnwUcWFPn1sA6QMPXmb9gdgC2IG3DIj4FfBcYCdwH/L7AOkcDz5Be/5qk7VE7BskngD1JX6pbAYfk+N4F/Bb4PLAGcDpwuaTla9Y9APggafttCBwObBsRw4H3AzMKvi4bAE7w1p3LJM0DbgFuAr4fadCiXUgf6J8A/5A0RdLGALmf/vvAUc0Kb1ZWRDwfERdHxKsR8RLwPWCnOsV9HvjfiHgkIhbkGMbllu8bwHBgM0B5mUZdR+dExPSIeAX4FvAJSUOBPwIbd8QHHAScHxF1f6UAc4C5wBnA1yPi+sZbZZE/RcSUiHgN+H/AdvmLtpE3gLcDYyLijYi4ORYfZOrkiHg2IuaSusbG5ef/Czg9Iu6MiIURcRbwGvDeLuvOjIj5wEJgeWBzSctGxIyI+HvB12UDwAneurNvRKwaEWMi4ov5w01EPBMRh0fEhqTW9SvA2XmdE0gJ8skiFTQqS9KKkk6X9JSkF4EpwKo52XY1Bvh57mKYR0qqAtaJiBtILf9fAv+UNFHSiAZhzayZfgpYFhiZk+0FwIG56+MA4JwmL3FkRKwWEe+IiJObLNttDBHxcn49azdZ50ekX0TXSHqim4O67TXTrwIr5+kxwNEd2y5vv/W61Fcbz+OkL/Djgeck/UFSs9hsADnBW69ExExS4uzo094NOFJSu6R2UqK4QNLXelHW0cCmwHsiYgSpmwVS4u5qJvD5/IXUcVshIm7LZZ8cEduQukk2AY5tEEptS3k0qWU8Jz8+i9R9shvwau5b76lXgBU7Hkhaq1EM+VfR6sCzjQqNiJci4uiI2ADYB/hqwb7xmcD3umy7FSPivJplFhtuNiLOjYj3kb4cAvhhgXpsgDjBWyH5wOcJkjaSNCQfKP0McEdeZDdSgh6Xb8+Suk9+2YuyhpP63eflA53HNQjtNOAbkrbIZa+SjwUgaVtJ75G0LCm5/pvUzVDPgZI2l7Qi8B3goohYCIsOlr5J6lJq1nqv535gC0nj8oHO47tZZi9J75O0HKkv/s78BVhXPlC6kSSRzkRaSOPX2eHXwGF5G0nSSpI+KGl4nXo2lbRr7qP/N+k9KlKPDRAneCvqdWAscB0piUwn9dceAov6zds7bqQP/gu5m6FHZQEnASuQWs93AFfVCyoiLiW1Iv+Qu3OmAx/Is0eQktgLpC6X54EfN3iN5wCTSF0aw0inbtY6G/gP4HcNyqgrIv5K+uK4Dvgb6RhHV+eSvtDmAtuQfjU0s3Eu82XgduBXETG5QDxTSf3wp5C20eN0vgfdWR74Ael9aSed3vrfBeKzASL/4YdZMZIOBsbnLgqzQc8teLMCcrfNF4GJAx2LWVFO8GZNSHo/MBv4J6kLxWyJUGoXjaSvAJ8jHW1/EDg0Iv5dWoVmZrZIaS14SeuQDlK1RcSWwFDgk2XVZ2Zmiyt7AKFlgBUkvUE6/7fh+bwjR46MsWPHlhySmVl1TJs2bU5EjOpuXmkJPiJmSfox8DTpfNlrIuKarstJGg+MBxg9ejRTp04tKyQzs8qR9FS9eWV20awGfJg0wNHawEqSDuy6XERMjIi2iGgbNarbLyEzM+uFMs+i2R14MiJmR8QbwCXA9iXWZ2ZmNcpM8E8D780DR4l0KfsjJdZnZmY1SkvwEXEncBFwD+kUySH4IhEzs5Yp9SyaiDiOxgNFmZlZSXwlq5lZRTnBm5lVlBO8mVlFlX0lq5lZJU2YMIH29nbWWmstTjzxxIEOp1tO8GZmvdDe3s6sWbMGOoyG3EVjZlZRTvBmZhXlBG9mVlFO8GZmFeUEb2ZWUU7wZmYV5QRvZlZRTvBmZhXlBG9mVlFO8GZmFeUEb2ZWUU7wZmYV5QRvZlZRpSV4SZtKuq/m9qKko8qqz8zMFlfacMER8RgwDkDSUGAWcGlZ9ZmZ2eJa1UWzG/D3iHiqRfWZmS31WpXgPwmc16K6zMyMFiR4ScsBHwIurDN/vKSpkqbOnj277HDMzJYarWjBfwC4JyL+2d3MiJgYEW0R0TZq1KgWhGNmtnRoRYI/AHfPmJm1XKkJXtKKwH8Cl5RZj5mZvVVpp0kCRMSrwBpl1mFmZt3zlaxmZhXlBG9mVlFO8GZmFeUEb2ZWUU7wZmYV5QRvZlZRTvBmZhXlBG9mVlFO8GZmFeUEb2ZWUU7wZmYV5QRvZlZRTvBmZhXlBG9mVlFO8GZmFeUEb2ZWUU7wZmYV5QRvZlZRZf8n66qSLpL0qKRHJG1XZn1mZtap1P9kBX4OXBURH5O0HLBiyfWZmVlWWoKXNALYETgEICJeB14vqz4zM1tcmV00GwCzgTMl3SvpDEkrlVifmZnVKDPBLwO8Czg1It4JvAJ8vetCksZLmipp6uzZs0sMx8xs6VJmgn8GeCYi7syPLyIl/MVExMSIaIuItlGjRpUYjpnZ0qW0BB8R7cBMSZvmp3YDHi6rPjMzW1zZZ9EcAfw+n0HzBHBoyfWZmVlWaoKPiPuAtjLrMDOz7vlKVjOzinKCNzOrKCd4M7OKcoI3M6soJ3gzs4pygjczqygneDOzinKCNzOrKCd4M7OKaprgJa0kaUie3kTShyQtW35oZmbWF0Va8FOAYZLWAa4njSczqcygzMys74okeEXEq8B+wC8i4iPA5uWGZWZmfVUowec/y/4U8Kf8XNmjUJqZWR8VSfBfBr4BXBoRD0naALix3LDMzKyvmrbEI2IKqR++4/ETwJFlBmVmZn3XNMFL2gQ4Bhhbu3xE7FpeWGZm1ldF+tIvBE4DzgAWlhuOmZn1lyIJfkFEnFp6JGZm1q+KJPgrJH0RuBR4rePJiJjbbEVJM4CXSC3/BRHhv+8zM2uRIgn+0/n+2JrnAtigYB27RMScHkVlZmZ9VuQsmvVbEYiZmfWvImfRLAt8AdgxPzUZOD0i3ihQfgDXSIq8zsTeBmpmZj1TpIvmVGBZ4Ff58UH5uc8VWHeHiHhW0tuAayU9ms+rX0TSeGA8wOjRowsHbmbWnVOOvqIl9cyb88qi+1bUefhP9unxOkUS/LYRsXXN4xsk3V+k8Ih4Nt8/J+lS4N3UXDSV500EJgK0tbVFoajNzKypIkMVLJS0YceDPFRB0/Ph8zDDwzumgT2A6b0N1MzMeqZIC/5Y4EZJTwACxpCGDG5mTeBSSR31nBsRV/U2UDMz65kiZ9FcL2ljYFNSgn80Il5rslrHmDVbN1vOzMzKUTfBS9o1Im6QtF+XWRtKIiIuKTk2MzPrg0Yt+J2AG4DuDt0G4ARvZjaI1U3wEXFcvi/S325mZoNMoy6arzZaMSJ+2v/hmJlZf2nURTO8ZVGYmVm/a9RFc0IrAzEzs/7VqIvm5EYrRoT/ts/MbBBr1EUzrWVRmJlZv2vURXNWKwMxM7P+1aiL5qSIOErSFaTz3hcTER8qNTIzM+uTRl005+T7H7ciEDMz61+Numim5fubWheOmZn1l6bDBUvaW9K9kuZKelHSS5JebEVwZmbWe0WGCz4J2A94MCL8hxxmZkuIIn/4MROY7uRuZrZkKdKCnwD8WdJNwKJx4D0WjZnZ4FYkwX8PeBkYBixXbjhmZtZfiiT41SNij9IjMTOzflWkD/46Sb1O8JKG5rNwruxtGWZm1nNFEvyXgKskze/laZJfBh7pXXhmZtZbTRN8RAyPiCERsUJEjMiPRxQpXNK6wAeBM/oaqJmZ9UyRFnxfnEQ6C+fNkusxM7MuSkvwkvYGnusY8qDBcuMlTZU0dfbs2WWFY2a21CmzBb8D8CFJM4A/ALtK+l3XhSJiYkS0RUTbqFGjSgzHzGzpUijB5zNh1pY0uuPWbJ2I+EZErBsRY4FPAjdExIF9jNfMzApqeh68pCOA44B/0tmXHsBWJcZlZmZ9VORCpy8Dm0bE872tJCImA5N7u76ZmfVc0cHG/lV2IGZm1r+KtOCfACZL+hMebMzMbIlRJME/nW/L4cHGzMyWGE0TfESc0IpAzMysf9VN8JJOioijJF1BOmtmMRHxoVIjMzOzPmnUgj8n3/+4FYGYmVn/qpvgO4YYiIibWheOmZn1l7IHGzMzswHiBG9mVlE9SvCShkgqNBa8mZkNrKYJXtK5kkZIWgl4GHhM0rHlh2ZmZn1RpAW/eUS8COwL/BkYDRxUZlA28CZMmMDBBx/MhAkTBjoUM+ulIleyLitpWVKCPyUi3pD0lvPirVra29uZNWvWQIdhZn1QpAV/OjADWAmYImkM0JM/3TYzswFQZKiCk4GTa556StIu5YVkZmb9ochB1jUl/UbSX/LjzYFPlx6ZmZn1SZEumknA1cDa+fFfgaNKisfMzPpJkQQ/MiIuIP9dX0QsABaWGpWZmfVZkQT/iqQ1yCNKSnov/ocnM7NBr8hpkl8FLgc2lHQrMAr4WLOVJA0DpgDL53ouiojj+hCrmZn1QJGzaO6RtBOwKSDgsYh4o0DZrwG7RsTL+Tz6WyT9JSLu6FvIZmZWRKM//NivzqxNJBERlzQqOCICeDk/XDbffIGUmVmLNGrB79NgXgANEzyApKHANGAj4JcRcWc3y4wHxgOMHj26WZFmZlZQoz/8OLSvhUfEQmCcpFWBSyVtGRHTuywzEZgI0NbW5ha+mVk/KXKQFUkfBLYAhnU8FxHfKVpJRMyTNBnYE5jeZHEzM+sHRa5kPQ3YHziCdJD148CYAuuNyi13JK0A7A482pdgzcysuCLnwW8fEQcDL0TECcB2wHoF1ns7cKOkB4C7gWsj4sreh2pmZj1RpItmfr5/VdLawPPA+s1WiogHgHf2ITYzM+uDIgn+ytzV8iPgHtIZNL8uMygzM+u7Ihc6fTdPXizpSmBYRFRyqIIJEybQ3t7OWmutxYknnjjQ4ZjZILbSciMWux+MGl3otC0wMyLa8+ODgY+SxoM/PiLmtijGlvG/GJlZUTtsWO9a0MGj0UHW04HXASTtCPwAOJs00NjE8kMzM7O+aNRFM7Smlb4/MDEiLiZ11dxXemRmZtYnjVrwQyV1fAHsBtxQM6/QBVJmZjZwGiXq84CbJM0hnSp5M4CkjfB48GZmg16jsWi+J+l60gVL1+TRISG1+o9oRXBmZtZ7Dbtauhu7PSL+Wl44ZmbWX4oMVWBmZksgJ3gzs4pygjczqygneDOzinKCNzOrKCd4M7OKcoI3M6soDzmwhHn6O//RknoWzF0dWIYFc59qSZ2jv/1g6XWYLW3cgjczq6jSEryk9STdKOkRSQ9J+nJZdZmZ2VuV2UWzADg6Iu6RNByYJunaiHi4xDrNzCwrrQUfEf+IiHvy9EvAI8A6ZdVnZmaLa0kfvKSxwDuBO7uZN17SVElTZ8+e3YpwzMyWCqUneEkrAxcDR0XEi13nR8TEiGiLiLZRo0aVHY6Z2VKj1AQvaVlScv99RFxSZl1mZra4Ms+iEfAb4JGI+GlZ9ZiZWffKbMHvABwE7Crpvnzbq8T6zMysRmmnSUbELYDKKt/MzBpbIoYq2ObYs1tSz/A5LzEUeHrOSy2pc9qPDi69DjNbenmoAjOzinKCNzOrKCd4M7OKcoI3M6soJ3gzs4pygjczqygneDOzinKCNzOrKCd4M7OKcoI3M6soJ3gzs4pygjczqygneDOzinKCNzOrKCd4M7OKWiLGgzezwWHChAm0t7ez1lprceKJJw50ONaEE7x1a+SwN4EF+d4saW9vZ9asWQMdhhVUWoKX9Ftgb+C5iNiyrHqsHMdsNW+gQzCzPiqzD34SsGeJ5ZuZWQOlJfiImALMLat8MzNrbMD74CWNB8YDjB49ekBjeXO5lRa7NzNbkg14go+IicBEgLa2thjIWF7ZeI+BrN7MrF/5PHgzs4pygjczq6jSEryk84DbgU0lPSPps2XVZWZmb1VaH3xEHFBW2WZm1tyAH2Q1s767acedWlLP/GWGgsT8Z55pSZ07Tbmp9DqqzH3wZmYV5QRvZlZRTvBmZhXlBG9mVlFO8GZmFeUEb2ZWUU7wZmYV5fPgzZrw39TZksoJ3qwJ/02dLamc4M2ssFUjFru3wc0J3swKO3Ch/4R9SeKDrGZmFeUWvC2xdvjFDi2pZ7l5yzGEIcycN7Mldd56xK2l12FLB7fgzcwqygnezKyinODNzCrKCd7MrKJKTfCS9pT0mKTHJX29zLrMyhIrBm+u9Caxos/9tiVLaWfRSBoK/BL4T+AZ4G5Jl0fEw2XVaVaGN3Z4Y6BDMOuVMlvw7wYej4gnIuJ14A/Ah0usz8zMaihKuuRY0seAPSPic/nxQcB7IuLwLsuNB8bnh5sCj5USUHEjgTkDHMNg4W3Ryduik7dFp8GwLcZExKjuZpR5oZO6ee4t3yYRMRGYWGIcPSJpakS0DXQcg4G3RSdvi07eFp0G+7Yos4vmGWC9msfrAs+WWJ+ZmdUoM8HfDWwsaX1JywGfBC4vsT4zM6tRWhdNRCyQdDhwNTAU+G1EPFRWff1o0HQXDQLeFp28LTp5W3Qa1NuitIOsZmY2sHwlq5lZRTnBm5lV1KBI8JJC0k9qHh8j6fgelrGzpO1rHk/K5+IXWfcjOYbNelJnD+Nrk3RyWeXXqXOhpPtqbh4uIpP08kDH0Fs17+t0SVdIWrUXZYyTtFcv1jtP0gOSvlLz3KqSnpek/Hi7/HlaNz9eRdJcSYXyjaSxkqbXmTdZUr+elihpTUnnSnpC0jRJt+ecsLOkK5use7ykY3pYX8v2vUGR4IHXgP0kjezNypKWAXYGtm+yaD0HALeQzvTpd5KWiYipEXFkGeU3MD8ixtXcflB0xbxNbXDqeF+3BOYCX+pFGeOAHiV4SWsB20fEVhHxs47nI2Ie0A68Iz+1PXAvnZ/H9wJ3RkTT//tr9X6Xv5QuA6ZExAYRsQ0pD6zbyjjKMlgS/ALS0eivdJ0haYyk63Or4XpJo/PzkyT9VNKNwPnAYcBXcsvm/+TVd5R0W/5m7rY1L2llYAfgs9Qk+PztfZOkCyT9VdIPJH1K0l2SHpS0YV5ulKSLJd2dbzvk54+XNFHSNcDZta0BSStLOjOX84Ckj+bnT5U0VdJDkk7ojw1b5zXP6Pgyzb8sJteJudG2P03SzXnb7J2fHyrpR3k7PCDp82W9hv6Q34frJd2T34sP5+fHSnpU0ln5dVwkacU879v59U3P26qj1TpZ0g/z/vHXmn2wbLcD6+QYNpR0VW6F3qz8i1TSx3O890uaonTa8neA/fPnZf8u22VYzf55r6Rd8qxrgLd1+Yx1uJXOhL498LMuj2+rV66kQyRdKOmKXEdtLCtI+kN+H84HVuj7JlvMrsDrEXFaxxMR8VRE/KJLHKtLuizHcYekrWpmby3pBkl/k/Rfeflu962Wi4gBvwEvAyOAGcAqwDHA8XneFcCn8/RngMvy9CTgSmBofnw8cExNmZOAC0lfYpuTxsXpru4Dgd/k6duAd+XpnYF5wNuB5YFZwAl53peBk/L0ucD78vRo4JGaeKYBK9SUd2We/mHH+vnxavl+9Xw/FJgMbNXH7boQuK/mtn9+fgYwMk+3AZPrxNxo21+Vt+3GpIvahpGGnPhmXmZ5YCqw/kDvXw32uWWAEfnxSOBx0hXYY0lXXe+Q5/22Y9/qeI/y9DnAPnl6MvCTPL0XcF2ZsdfsJxeShgQBuB7YOE+/B7ghTz8IrJOnV833hwCn1Cn/aODMPL0Z8HR+f8cC0+uscwjpVGhIrfdhwC358bWkRFqv3EPyPtSx/y+qB/hqTblbkRqDbf24LY8EflZn3s50fmZ/ARyXp3cF7qv5zNxP+uIZCcwE1q63b9W+f624DZYWPBHxInA2aYPX2o6URCF9oN5XM+/CiFjYoNjLIuLNSCNYrllnmQNIA6GR7w+omXd3RPwjIl4D/k5n6+JB0k4IsDtwiqT7SBdyjZA0PM+7PCLmd1Pn7qSRNgGIiBfy5Cck3UP6gGxB+mLqi65dNOcXWKc25kbb/oK8bf8GPEH6wO4BHJy3xZ3AGqQvgMFKwPclPQBcR2oJd+wnMyOi489Rf0fna99F0p2SHiR90LeoKe+SfD+Nzv2jDCvkbfw8sDpwrdIv0e2BC/O800mNE0it60m5dTm0QPnvI73fRMSjwFPAJk3WuRXYXtL6wIyI+DepB2RlYBvgriblXhsRc7spd0fS9iciHgAeKBB/r0n6Zf6lc3eXWbWx3wCsIWmVPO+PETE/IuYAN5IGWmy0b7XMYOtnPQm4BzizwTK1J+6/0qS812qm3zI2jqQ1SB/SLSUFaecPSRO6Wf/Nmsdv0rnthgDbdU3k+Zd7vfjU5XWQPxjHANtGxAuSJpFaN2VYQGf3XNc6Gm3TqDPd8VjAERFxdd/Ca5lPAaOAbSLiDUkz6Nweb3l9koYBvyK1IGcqnQhQu/069o+FlPvZmh8R43KCuZLUBz8JmBcR47ouHBGHSXoP8EHgPklvWaaL7saRaigi/iZpNWAfUrcRpC+6Q4EnI+Llju6sOorud/3tIeCjiyqK+FLuvpzaZblGY2t191lotG+1zKBpwQPkb/ALSP3hHW6js2/8U6SDod15CRheZ149HwPOjogxETE2ItYDnmTxlmoz1wCLRsgs8OHpbp3VSF1UrwD/krQm8IEexNBTM0itKqjZubvRaNt/XNIQpWMRG5BGAb0a+IKkZQEkbSJppf4MvJ+tAjyXP4C7AGNq5o2WtF2e7jgI3/EBnZNbpoXO0ipLRPyL9Iv3GGA+8KSkj0NqOkvaOk9vGBF3RsS3SSMfrkfjz8sU0vuNpE1IXY9FRnm9ndR9eXvN46NI+1Fvy61dZ0tSN01/ugEYJukLNc+t2CSOnYE5udcB4MP5+MIapG6du2m8b7XMoErw2U9IfVYdjgQOzT91DiLtQN25AvhInQNA9RwAXNrluYuB/9uDeI8E2vLBl4dJB3ub+R9gtY4DX8AuEXE/qWvmIVKf762NCihoBS1+mmTHWTQnAD+XdDOptVlPo23/GHAT8BfgsPyT/AzgYeAepdPcTmfw/UrsOFPjNeD3pPduKunD+2jNYo8An86vfXXg1Ehni/ya1EV3GemDPKAi4l5SH/AnSa/hs3mfeojO/1/4UT7QN52UqO4ndSVs3t1BVtKvlKG5G+p84JDcTdnMraQvj47W7+2kL/+OBN+bck8FVs7vwwRSV0+/idQpvi+wk6QnJd0FnAV8rcuix5M/58APgE/XzLsL+BNwB/DdiHiWxvtWy3ioAuux3H10ZURcNNCx9EZu2f46It5dZ/5Y0uvbsqWBmfWzwdiCNyuNpMOA84BvDnQsZmVzC97MrKLcgjczqygneDOzinKCNzOrKCd4W+Jp8dEVL1QeN6bB8ovG4uny/KKRASV9R9LuDcooPFqp2UBxgrcqqB1d8XWKXYvQUER8OyKu63tob5UvQvJnz0rnncyq5mZgI3UZy1vSKZIOqVnuWKWRH++StFHXQmpb6EojiT6cL2b7cc1i3Y5WKulYdY6oeUJ+bqykRyT9ijQcx3q5jun5IqS3jKRq1leD7ipDs97KV6h+gDTSZTMvRsS7JR1MGgNp7zplrg58BNgsIkKL/7nG20nDWmxGGmjuIkl7kAZY6xhw6nJJO5JGTtwUODQivihpG9IIj1vmemrLNesXbsFbFXSMrjiVlEh/U2Cd82rut2uw3IvAv4EzJO0HvFozr7vRSvfIt3tJLfXN6BxR86mIuCNPPwFsIOkXkvbM9Zj1K7fgrQrmdx1FUVLtiJnw1pH8Go2M2TkjYoGkdwO7kcZ7OZw0Ail0P1qpgP+NiNO7xDOWmhET84ihWwPvJ40G+QnSmPtm/cYteKuqp0iDaS2vNKzubl3m719zfzt15FEjV4mIP5NGRhzXpN6rgc/k9ZC0jqS3dVPuSGBIRFwMfAt4V9NXZNZDbsFbJeXx2i8g/UHE30hdJrWWl3QnqZFzQNf1awwH/qg0Frzo5m8lu9R7jaR3ALcrDX/+Mulfw7qO2rkOcGbN2TTfaP6qzHrGY9GYmVWUu2jMzCrKCd7MrKKc4M3MKsoJ3sysopzgzcwqygnezKyinODNzCrq/wNArTjlgkS0rwAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "PS = sns.barplot(data = PS4ds_Publisher)\n",
    "PS.set(xlabel=\"Publishers\", ylabel = \"Sales in millions\")\n",
    "plt.title(\"PS4 Sales by Publishers\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "6ac611c7-8ab5-4fbd-99fe-690c60ad13cf",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Text(0.5, 1.0, 'xBox Sales by Publisher')"
      ]
     },
     "execution_count": 32,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXgAAAEWCAYAAABsY4yMAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAAAd8klEQVR4nO3debgcVbnv8e+PMIQhDCFbwpREEVBE4EhAGWQ+iIpy5OhFRCb15KAiokL0eHmQ0YtRNCqKIGoYBARRBBxAwQAyJ8yjIgZDdB8IGMaIJLz3j7WaXdnp7l17qL07xe/zPP10VVfVWm9XV7+9elX1akUEZmZWP8uNdABmZlYNJ3gzs5pygjczqykneDOzmnKCNzOrKSd4M7OacoK32pA0Q9JJnV7mAGI4TtJ5bZbPkbRHnv6ipLNKlDlT0seGMk7rPE7wVkpOCP+U9JykpyVdJ+nNFdSzgaRLJM3P9dwj6ZChrmckSApJz+d9OE/S1yWNGso6IuLLEeHEbYATvPXP4RGxGrA2MBM4t4I6zgXmAhNzPQcB/1tBPSNly7wPdwc+BPzXCMczKEqcRzqUXxgDQNJGkp6S9JY8v15uRe/Se92IWARcCGxW2H4lSdMl/S3fpufHVpR0p6RP5fVGSbpB0rEtQtkGmBERz0fEooi4IyJ+XajnYkndhW8Rb2rznPbOdS+QdKOkLQrLPp9b0c9KekjS7m12zzhJv83rXitpYi7jO5JO7VXn5ZKObFMWABHxIHA9sLmkXSQ91qucV7pdstGSfpJjuF3Sli2e8yvdOZJGSzpP0pN5H9wmaZ3C6hPza/GspKskjSuU87a8zxZIuqt4HORvcydLugF4AXhdX8/XRoYTvAEQEX8GPg/8WNIqwI9IiXZm73UlrQgcANxcePj/Am8DtgK2BLYFjomIfwEfBk6Q9EbgC8Ao4OQWodwMfEfSByVNaLL818DGwGuA24EfNyskf1D9EPhv0jeBM4DL8ofOpsDhwDYRMQZ4BzCnRTzk53oiMA64s1Dn2cD+jRZsTpC7Axe0KasR32bA24E7+lo32we4GBgLnA9cKmmFPrY5GFgD2JC0Dw4DFhaWfwg4lLQvVwSOyrGtD/wSOCnXdxRwiaSuwrYHAlOAMcCjJZ+DDbeI8M23V27AZcA9wN3ASoXHZ5JaawuAfwFPA7sXlv8ZeFdh/h3AnML854AHgX8AG7epfy3gFOA+YDEpoW7TYt01gQDWyPMzgJPy9OnAib3WfwjYGXg98DiwB7BCH/tjBnBhYX61HNeGef4B4N/z9OHAr9qUFcAzeR/8mZRAlwN2AR7rte4cYI88fRxwc2HZcsDfgbe3WPe8PP0R4EZgiyaxzCR9ADfmPwH8Jk9/Hji31/pXAgcXtj1hpI9V3/q+uQVvvX0f2Bz4dkS82GvZERGxJjAa2Bv4aaHbYz2WbMk9mh9rOBuYREqAf2pVeUT8IyK+EBFvAtYhJfhLc1/vKEmnSPqzpGfoaXWPa1LUROBzuYthgaQFpJbsehHxMHAkKRk+LulCSes1KaNhbiG+54CnCs/tbNI3FPJ9X+cl3hIRa0XERhFxTES83Mf6zWJ4GXiMJfdvM+eSEvOFudtsWq9Wf3dh+gXShxekffeBXvtuR2DdZvFY53KCt1dIWg2YDvwAOE7S2GbrRcTLEXE98DCwZ374b6TE0DAhP9bwXeAK4B2SdiwTT0TMB75GSmRjSV0K+5Ba3muQPjAA1GTzucDJEbFm4bZKRFyQyz4/InbMMQfwlTahbNiYyPtobOG5nQfsk/vE3whcWua59fI8sEqhjlFAV691ijEsB2zAkvt3KRHxUkQcHxGbAduTPpQPKhHPXFILvrjvVo2IU4rFlyjHRpgTvBV9E5gd6TK7XwLfa7WipO1IJ1nvyw9dABwjqSv3RR9LSn5IOhDYGjgEOAI4OyfKZuV+RdLmkpaXNAb4OPBwRDxJ6u99EXiSlBC/3Oa5fB84TNJbc+t/VUnvljRG0qaSdpO0EvBPUr/04jZlvUvSjvncw4nALRExFyAiHgNuI7WWL4mIhW3KaeWPpJOo784t7GOAlXqts7WkfSUtT/r28SJLngNZiqRdJb05f2A8A7xE++fZcB7wHknvyN+aRucTwRv083nZCHOCNwAk7QPsRToRB/BZ4C2SDiisdprSNdzPkRLaMdFzhctJwCxS3/09pBOgJ+UTpdOBgyLiuYg4P6/3jRahrAL8nNTX/wiphf3evOwcUtfPPOB+2iS4iJhFugTxNFKf98OkDxhIyfMUYD6pm+I1wBdblUU6qfklUtfM1qSTrkVnA29mgJeNRsTTpD7ws0jP7XlSF0zRL4D98nM5ENg3Il7qo+jxwE9Jyf0B4Fryh24f8cwlfVP6IvAEqUV/NM4XyxxF+JuW2WBI2omUOCf1o0/drHL+RDYbhNyl8mngLCd36zRO8GYDlK/rX0C6umT6iAZj1oS7aMzMasoteDOzmlp+pAMoGjduXEyaNGmkwzAzW2bMnj17fkT0/t0E0GEJftKkScyaNWukwzAzW2ZIajkWkLtozMxqygnezKymnODNzGrKCd7MrKac4M3MasoJ3sysppzgzcxqygnezKymOuqHTmZmy4qpU6fS3d3N+PHjmTZt2kiH05QTvJnZAHR3dzNv3ryRDqMtd9GYmdWUE7yZWU05wZuZ1ZQTvJlZTTnBm5nVlBO8mVlNOcGbmdWUE7yZWU05wZuZ1ZQTvJlZTTnBm5nVlBO8mVlNVTrYmKQ5wLPAYmBRREyusj4zM+sxHKNJ7hoR84ehHjMzK3AXjZlZTVWd4AO4StJsSVOarSBpiqRZkmY98cQTFYdjZvbqUXWC3yEi3gK8E/ikpJ16rxARZ0bE5IiY3NXVVXE4ZmavHpUm+Ij4W75/HPg5sG2V9ZmZWY/KErykVSWNaUwDewL3VlWfmZktqcqraNYBfi6pUc/5EfGbCuszM7OCyhJ8RDwCbFlV+WZm1p4vkzQzqykneDOzmnKCNzOrKSd4M7OacoI3M6spJ3gzs5pygjczqykneDOzmnKCNzOrKSd4M7OacoI3M6spJ3gzs5pygjczqykneDOzmnKCNzOrKSd4M7OacoI3M6spJ3gzs5pygjczqykneDOzmnKCNzOrKSd4M7OacoI3M6spJ3gzs5pygjczqykneDOzmnKCNzOrKSd4M7OacoI3M6upyhO8pFGS7pB0RdV1mZlZj+FowX8aeGAY6jEzs4JKE7ykDYB3A2dVWY+ZmS2t6hb8dGAq8HKrFSRNkTRL0qwnnnii4nDMzF49KkvwkvYGHo+I2e3Wi4gzI2JyREzu6uqqKhwzs1edKlvwOwDvlTQHuBDYTdJ5FdZnZmYFlSX4iPifiNggIiYBHwSuiYgPV1WfmZktydfBm5nVVJ8JXtKqkpbL05tIeq+kFfpTSUTMjIi9BxqkmZn1X5kW/HXAaEnrA1cDhwIzqgzKzMwGr0yCV0S8AOwLfDsi3gdsVm1YZmY2WKUSvKTtgAOAX+bHlq8uJDMzGwplEvyngf8Bfh4R90l6HfD7asMyM7PB6rMlHhHXkfrhG/OPAEdUGZSZmQ1enwle0ibAUcCk4voRsVt1YZmZ2WCV6Uu/GPgeacCwxdWGY2ZmQ6VMgl8UEadXHomZmQ2pMidZL5f0CUnrShrbuFUemZmZDUqZFvzB+f7owmMBvG7owzEzs6FS5iqa1w5HIGZmNrTKXEWzAvBxYKf80EzgjIh4qcK4zMxskMp00ZwOrAB8N88fmB/7WFVBmZnZ4JVJ8NtExJaF+Wsk3VVVQGZmNjTKXEWzWNJGjZk8VIGvhzcz63BlWvBHA7+X9AggYCJpyGAzM+tgZa6iuVrSxsCmpAT/YES8WHlkZmY2KC0TvKTdIuIaSfv2WrSRJCLiZxXHZmbWb6d97vJhqWfB/OdfuR+OOg8/9T393qZdC35n4BqgWakBOMGbmXWwlgk+Ir6U793fbma2DGrXRfPZdhtGxNeHPpyRNXXqVLq7uxk/fjzTpk0b6XDMzAalXRfNmGGLokN0d3czb968kQ7DzGxItOuiOX44AzEzs6HVrovmW+02jAj/bZ+ZWQdr10Uze9iiMDOzIdeui+bs4QzEzMyGVrsumukRcaSky0nXvS8hIt5baWRmZjYo7bpozs33XxuOQMzMbGi166KZne+vHb5wzMxsqPQ5XLCkvSXdIekpSc9IelbSMyW2Gy3pVkl3SbpPki+7NDMbRmWGC54O7AvcExFL9cW38SKwW0Q8l//27w+Sfh0RNw8gTjMz66cyCX4ucG8/kzt5/efy7Ar51q8yzMxs4Mok+KnAryRdS2qVA+XGopE0inQ9/euB70TELU3WmQJMAZgwYULJsM3MrC9l/rLvZOAFYDRpfJrGrU8RsTgitgI2ALaVtHmTdc6MiMkRMbmrq6t04GZm1l6ZFvzYiNhzMJVExAJJM4G9gHsHU5aZmZVTpgX/O0n9TvCSuiStmadXBvYAHuxvOWZmNjBlWvCfBKZKehF4ifS/rBERq/ex3brA2bkffjngooi4YlDRmplZaWX+dHtA48JHxN3Avw1kWzMzG7wyXTRmZrYMcoI3M6spJ3gzs5oqc5K18YOldYrrR8RfqwrKzMwGr88EL+lTwJeA/wVezg8HsEWFcZmZ2SCVacF/Gtg0Ip6sOhgzMxs6Zfrg5wJPVx2ImZkNrTIt+EeAmZJ+ST8HGzMzs5FTJsH/Nd9WzDczM1sGlPklq/+JycxsGdQywUuaHhFHSrqcJn/UERHvrTQyMzMblHYt+HPz/deGIxAzMxtaLRN8RMzO99cOXzhmZjZUPFSBmVlNOcGbmdVUvxK8pOUk9fVHH2Zm1gH6TPCSzpe0uqRVgfuBhyQdXX1oZmY2GGVa8JtFxDPAfwC/AiYAB1YZlJmZDV6ZBL+CpBVICf4XEfESTa6LNzOzzlImwZ8BzAFWBa6TNBF4psqgzMxs8MoMVfAt4FuFhx6VtGt1IZmZ2VAoc5J1HUk/kPTrPL8ZcHDlkZmZ2aCU6aKZAVwJrJfn/wgcWVE8ZmY2RMok+HERcRH57/oiYhGwuNKozMxs0Mok+OclrU2+ckbS2/A/PJmZdbwyf/jxWeAyYCNJNwBdwPsrjcrMzAatzFU0t0vaGdgUEPBQvhbezMw6WLs//Ni3xaJNJBERP6soJjMzGwLtWvDvabMsACd4M7MO1u4PPw4dTMGSNgTOAcaTrsA5MyK+OZgyzcysvDInWZH0buBNwOjGYxFxQh+bLQI+l/vwxwCzJf02Iu7vb5BbH31OfzcZkDHzn2UU8Nf5zw5LnbO/elDldZjZq1eZX7J+D9gP+BTpJOsHgIl9bRcRf4+I2/P0s8ADwPqDitbMzEorcx389hFxEPCPiDge2A7YsD+VSJoE/BtwS5NlUyTNkjTriSee6E+xZmbWRpkEvzDfvyBpPeAl4LVlK5C0GnAJcGQeV34JEXFmREyOiMldXV1lizUzsz6U6YO/QtKawFeB20lX0Hy/TOF5HPlLgB/7skozs+FV5odOJ+bJSyRdAYyOiD6HKpAk4AfAAxHx9cGFaWZm/dWyi0bSNpLGF+YPAi4CTpQ0tkTZO5D+2m83SXfm27sGHbGZmZXSrgV/BrAHgKSdgFNIV9JsBZxJH+PRRMQfSFfdmJnZCGiX4EdFxFN5ej/SD5UuIXXV3Fl5ZGZmNijtrqIZJanxAbA7cE1hWakfSJmZ2chpl6gvAK6VNJ90qeT1AJJej8eDNzPreO3GojlZ0tXAusBVERF50XKkvngzM+tgbbtaIuLmJo/9sbpwzMxsqJT5JauZmS2DnODNzGrKV8OYmQ3AqiuuvsR9J3KCt6amTp1Kd3c348ePZ9q0aSMdjlnH2WGjVv9q2jmc4K2p7u5u5s2bN9JhmNkguA/ezKymnODNzGrKCd7MrKac4M3MasoJ3sysppzgzcxqygnezKymnODNzGrKCd7MrKac4M3MasoJ3sysppzgzcxqygnezKymnODNzGrKCd7MrKac4M3MasoJ3sysppzgzcxqygnezKymKkvwkn4o6XFJ91ZVh5mZtVZlC34GsFeF5ZuZWRuVJfiIuA54qqryzcysveVHOoBO8vKKqy5x34n+esKbh6WeRU+NBZZn0VOPDkudE469p/I6zF5tRjzBS5oCTAGYMGHCiMby/MZ7jmj9ZmZDacSvoomIMyNickRM7urqGulwzMxqY8QTvJmZVaPKyyQvAG4CNpX0mKSPVlWXmZktrbI++IjYv6qyzcysb+6iMTOrKSd4M7OacoI3M6spJ3gzs5pygjczqykneDOzmnKCNzOrKSd4M7OacoI3M6spJ3gzs5pygjczqykneDOzmnKCNzOrqRH/RyczW3ZMnTqV7u5uxo8fz7Rp00Y6HOuDE7yZldbd3c28efNGOgwryV00ZmY15Ra8NTVu9MvAonxvZssiJ3hr6qgtFox0CGY2SO6iMTOrKSd4M7OacoI3M6sp98Gb1cC1O+08LPUsXH4USCx87LFhqXPn666tvI46cwvezKymnODNzGrKCd7MrKac4M3MasoJ3sysppzgzcxqypdJmllpa0YscW+dzQnezEr78GIPPrcsqbSLRtJekh6S9LCkL1RZl5mZLamyFrykUcB3gH8HHgNuk3RZRNxfVZ1mVfC/GNmyqsoumm2BhyPiEQBJFwL7AE7wtkzxvxjZskpR0ckSSe8H9oqIj+X5A4G3RsThvdabAkzJs5sCD1USUHnjgPkjHEOn8L7o4X3Rw/uiRyfsi4kR0dVsQZUteDV5bKlPk4g4Ezizwjj6RdKsiJg80nF0Au+LHt4XPbwvenT6vqjyJOtjwIaF+Q2Av1VYn5mZFVSZ4G8DNpb0WkkrAh8ELquwPjMzK6isiyYiFkk6HLgSGAX8MCLuq6q+IdQx3UUdwPuih/dFD++LHh29Lyo7yWpmZiPLY9GYmdWUE7yZWU11RIKXFJJOLcwfJem4fpaxi6TtC/Mz8rX4ZbZ9X47hDf2ps5/xTZb0rarKb1HnYkl3Fm4eLiKT9NxIxzBQhdf1XkmXS1pzAGVsJeldA9juAkl3S/pM4bE1JT0pSXl+u/x+2iDPryHpKUml8o2kSZLubbFspqQhvSxR0jqSzpf0iKTZkm7KOWEXSVf0se1xko7qZ33Ddux1RIIHXgT2lTRuIBtLWh7YBdi+j1Vb2R/4A+lKnyEnafmImBURR1RRfhsLI2Krwu2UshvmfWqdqfG6bg48BXxyAGVsBfQrwUsaD2wfEVtExDcaj0fEAqAbeGN+aHvgDnrej28DbomIPkcqG+7jLn8oXQpcFxGvi4itSXlgg+GMoyqdkuAXkc5Gf6b3AkkTJV2dWw1XS5qQH58h6euSfg/8BDgM+Exu2bw9b76TpBvzJ3PT1ryk1YAdgI9SSPD50/taSRdJ+qOkUyQdIOlWSfdI2iiv1yXpEkm35dsO+fHjJJ0p6SrgnGJrQNJqkn6Uy7lb0n/mx0+XNEvSfZKOH4od2+I5z2l8mOZvFjNbxNxu339P0vV53+ydHx8l6at5P9wt6b+reg5DIb8OV0u6Pb8W++THJ0l6UNLZ+Xn8VNIqedmx+fndm/dVo9U6U9JX8vHxx8IxWLWbgPVzDBtJ+k1uhV6v/I1U0gdyvHdJuk7psuUTgP3y+2W/XvtldOH4vEPSrnnRVcBrer3HGm6gJ6FvD3yj1/yNrcqVdIikiyVdnusoxrKypAvz6/ATYOXB77Il7Ab8KyK+13ggIh6NiG/3imOspEtzHDdL2qKweEtJ10j6k6T/yus3PbaGXUSM+A14DlgdmAOsARwFHJeXXQ4cnKc/Alyap2cAVwCj8vxxwFGFMmcAF5M+xDYjjYvTrO4PAz/I0zcCb8nTuwALgHWBlYB5wPF52aeB6Xn6fGDHPD0BeKAQz2xg5UJ5V+TprzS2z/Nr5fux+X4UMBPYYpD7dTFwZ+G2X358DjAuT08GZraIud2+/03etxuTftQ2mjTkxDF5nZWAWcBrR/r4anPMLQ+snufHAQ+TfoE9ifSr6x3ysh82jq3Ga5SnzwXek6dnAqfm6XcBv6sy9sJxcjFpSBCAq4GN8/RbgWvy9D3A+nl6zXx/CHBai/I/B/woT78B+Gt+fScB97bY5hDSpdCQWu+jgT/k+d+SEmmrcg/Jx1Dj+H+lHuCzhXK3IDUGJw/hvjwC+EaLZbvQ8579NvClPL0bcGfhPXMX6YNnHDAXWK/VsVV8/Ybj1ikteCLiGeAc0g4v2o6URCG9oXYsLLs4Iha3KfbSiHg50giW67RYZ3/gwjx9YZ5vuC0i/h4RLwJ/pqd1cQ/pIATYAzhN0p2kH3KtLmlMXnZZRCxsUucepJE2AYiIf+TJ/yPpdtIb5E2kD6bB6N1F85MS2xRjbrfvL8r79k/AI6Q37J7AQXlf3AKsTfoA6FQCvizpbuB3pJZw4ziZGxE35Onz6Hnuu0q6RdI9pDf6mwrl/Szfz6bn+KjCynkfPwmMBX6r9E10e+DivOwMUuMEUut6Rm5djipR/o6k15uIeBB4FNikj21uALaX9FpgTkT8k9QDshqwNXBrH+X+NiKealLuTqT9T0TcDdxdIv4Bk/Sd/E3ntl6LirFfA6wtaY287BcRsTAi5gO/Jw202O7YGjad1s86Hbgd+FGbdYoX7j/fR3kvFqaXGhtH0tqkN+nmkoJ08IekqU22f7kw/zI9+245YLveiTx/c28Vn3o9D/Ib4yhgm4j4h6QZpNZNFRbR0z3Xu452+zRaTDfmBXwqIq4cXHjD5gCgC9g6Il6SNIee/bHU85M0GvguqQU5V+lCgOL+axwfi6n2vbUwIrbKCeYKUh/8DGBBRGzVe+WIOEzSW4F3A3dKWmqdXpqNI9VWRPxJ0lrAe0jdRpA+6A4F/hIRzzW6s1ooe9wNtfuA/3yloohP5u7LWb3Waze2VrP3Qrtja9h0TAseIH+CX0TqD2+4kZ6+8QNIJ0ObeRYY02JZK+8HzomIiRExKSI2BP7Cki3VvlwFvDJCZok3T7Nt1iJ1UT0PPC1pHeCd/Yihv+aQWlVQOLibaLfvPyBpOaVzEa8jjQJ6JfBxSSsASNpE0qpDGfgQWwN4PL8BdwUmFpZNkLRdnm6chG+8Qefnlmmpq7SqEhFPk77xHgUsBP4i6QOQms6StszTG0XELRFxLGnkww1p/365jvR6I2kTUtdjmVFebyJ1X95UmD+SdBwNtNziNpuTummG0jXAaEkfLzy2Sh9x7ALMz70OAPvk8wtrk7p1bqP9sTVsOirBZ6eS+qwajgAOzV91DiQdQM1cDryvxQmgVvYHft7rsUuAD/Uj3iOAyfnky/2kk719OQlYq3HiC9g1Iu4idc3cR+rzvaFdASWtrCUvk2xcRXM88E1J15Nam6202/cPAdcCvwYOy1/JzyKN93+70mVuZ9B53xIbV2q8CPyY9NrNIr15Hyys9gBwcH7uY4HTI10t8n1SF92lpDfyiIqIO0h9wB8kPYeP5mPqPtL/LwB8NZ/ou5eUqO4idSVs1uwkK+lbyqjcDfUT4JDcTdmXG0gfHo3W702kD/9Ggh9IuacDq+XXYSqpq2fIROoU/w9gZ0l/kXQrcDbw+V6rHkd+nwOnAAcXlt0K/BK4GTgxIv5G+2Nr2HioAuu33H10RUT8dKRjGYjcsv1+RGzbYvkk0vPbfFgDMxtindiCN6uMpMOAC4BjRjoWs6q5BW9mVlNuwZuZ1ZQTvJlZTTnBm5nVlBO81YqWHGnxYuUxZNqs/8q4PL0ef2WUQEknSNqjTRmlRy41G05O8FY3xZEW/0W53yW0FRHHRsTvBh/a0vIPkvw+tEr4wLI6ux54vXqN6y3pNEmHFNY7WmkUyFslvb53IcUWutKoovfnH7Z9rbBa05FLJR2tntE1j8+PTZL0gKTvkobm2HBon7ZZ0nG/MjQbCvnXqu8kjXrZl2ciYltJB5HGQ9q7RZljgfcBb4iI0JJ/tLEuaYiLN5AGnfuppD1Jg601Bp+6TNJOpFEUNwUOjYhPDODpmZXiFrzVTWOkxVmkRPqDEttcULjfrs16zwD/BM6StC/wQmFZs5FL98y3O0gt9TfQM7rmoxFxc4nYzAbMLXirm4W9R1SUVBw9E5Ye1a/dKJk9CyIWSdoW2J009svhpNFIofnIpQL+X0Sc0SueSfQ9EqrZoLkFb68Gj5IG1lopD7G7e6/l+xXub6KFPILkGhHxK9IoiVv1Ue+VwEfydkhaX9Jr+h++2cC4BW+1l8duv4j0ZxF/InWZFK0k6RZSg2f/3tsXjAF+oTQuvGjyF5O96r1K0huBm5SGQn+O9A9i7UbwNBsyHovGzKym3EVjZlZTTvBmZjXlBG9mVlNO8GZmNeUEb2ZWU07wZmY15QRvZlZT/x9+MFwaKrnAEwAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "xbox = sns.barplot(data = xBoxds_Publisher)\n",
    "xbox.set(xlabel=\"Publisher\", ylabel = \"Sales in millions\")\n",
    "plt.title(\"xBox Sales by Publisher\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d03ae567-e4fa-4840-a240-4ac35c5da05a",
   "metadata": {},
   "source": [
    "# ***Research EDA:***  "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "dff4976e-9418-4663-a944-d02ebab4741b",
   "metadata": {},
   "source": [
    "### Which region of the world helps make publisher maximum profit?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e5d96286-f974-46e8-9316-43cef3166160",
   "metadata": {},
   "source": [
    "#### As per the analysis above, referring to the barplot it shows that PS4 has more publisher sales than xBox globally. This shows that publishers earn more from PS4 games as compared to xBox games, infact xBox publishers have really low business in Japan. This brings to the conclusion that PS4 publisher have more business and hence make more profit as compared to xBox game publishers. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4368d1ee-704f-440b-ab6c-7ce624f834fa",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "731ae364-0514-4971-bf56-75256e5912c7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
